name: sway
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.1
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.8
  pinput: ^3.0.1
  encrypt: ^5.0.3
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  country_code_picker: ^3.2.0
  flutter_svg: ^2.0.17
  flutter_typeahead:
  http: ^1.3.0
  socket_io_client: ^3.0.2
  qr_flutter: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
